### ISSUE TITLE
Installing Calligra error

### ISSUE THREAD

**Issue by kamilko** [adymo/homebrew-kde#36]
I'm having latest homebrew installed on Lion. With fixed path (/usr/local/bin before /usr/bin) and while I'm trying to install calligra I'm getting such error:
```
$ brew install calligra
Error: /usr/local/Library/Taps/adymo/homebrew-kde/calligra.rb:64: syntax error, unexpected tSTRING_BEG, expecting tAMPER
        system "cmake", *cmake_args, "-DBUNDLE_INSTALL_DIR=."
                                      ^
/usr/local/Library/Taps/adymo/homebrew-kde/calligra.rb:72: syntax error, unexpected tSTRING_BEG, expecting tAMPER
                      "-DBUNDLE_INSTALL_DIR=#{bin}",
                       ^
/usr/local/Library/Taps/adymo/homebrew-kde/calligra.rb:72: syntax error, unexpected ',', expecting kEND
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Homebrew/formulary.rb:65:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:27:in `install'
/usr/local/Library/brew.rb:131:in `send'
/usr/local/Library/brew.rb:131
```

Homebrew-kde was installed as in UG.

**Comment by adymo** [comment]
Calligra is no longer part of this repo
