### ISSUE TITLE
Cannot tap adymo/kde

### ISSUE THREAD

**Issue by yafshar** [adymo/homebrew-kde#77]
There is an issue on Mac OS X:
Error: Cannot tap adymo/kde: invalid syntax in tap!

ProductName:            Mac OS X
ProductVersion: 10.11.6

==> Tapping adymo/kde
Cloning into '/usr/local/Library/Taps/adymo/homebrew-kde'...
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/akonadi.rb:6:in `class:Akonadi'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/akonadi.rb:6:in `class:Akonadi'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/akonadi.rb:6:in `class:Akonadi'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:6:in `class:Attica'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:6:in `class:Attica'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:6:in `class:Attica'
Please report this to the adymo/kde tap!

Error: Invalid formula: /usr/local/Library/Taps/adymo/homebrew-kde/base_kde_formula.rb
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/grantlee.rb:7:in `class:Grantlee'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/grantlee.rb:7:in `class:Grantlee'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/grantlee.rb:7:in `class:Grantlee'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kactivities.rb:6:in `class:Kactivities'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kactivities.rb:6:in `class:Kactivities'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kactivities.rb:6:in `class:Kactivities'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kate.rb:6:in `class:Kate'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kate.rb:6:in `class:Kate'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kate.rb:6:in `class:Kate'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kde-phonon.rb:6:in `class:KdePhonon'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kde-phonon.rb:6:in `class:KdePhonon'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kde-phonon.rb:6:in `class:KdePhonon'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kde-runtime.rb:6:in `class:KdeRuntime'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kde-runtime.rb:6:in `class:KdeRuntime'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kde-runtime.rb:6:in `class:KdeRuntime'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdelibs.rb:6:in `class:Kdelibs'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdelibs.rb:6:in `class:Kdelibs'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdelibs.rb:6:in `class:Kdelibs'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdepimlibs.rb:6:in `class:Kdepimlibs'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdepimlibs.rb:6:in `class:Kdepimlibs'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdepimlibs.rb:6:in `class:Kdepimlibs'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-pg-qt.rb:6:in `class:KdevelopPgQt'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-pg-qt.rb:6:in `class:KdevelopPgQt'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-pg-qt.rb:6:in `class:KdevelopPgQt'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-php-docs.rb:6:in `class:KdevelopPhpDocs'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-php-docs.rb:6:in `class:KdevelopPhpDocs'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-php-docs.rb:6:in `class:KdevelopPhpDocs'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-php.rb:6:in `class:KdevelopPhp'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-php.rb:6:in `class:KdevelopPhp'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-php.rb:6:in `class:KdevelopPhp'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-python.rb:6:in `class:KdevelopPython'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-python.rb:6:in `class:KdevelopPython'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-python.rb:6:in `class:KdevelopPython'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-ruby.rb:6:in `class:KdevelopRuby'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-ruby.rb:6:in `class:KdevelopRuby'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop-ruby.rb:6:in `class:KdevelopRuby'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop.rb:6:in `class:Kdevelop'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop.rb:6:in `class:Kdevelop'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevelop.rb:6:in `class:Kdevelop'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevplatform.rb:6:in `class:Kdevplatform'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevplatform.rb:6:in `class:Kdevplatform'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/kdevplatform.rb:6:in `class:Kdevplatform'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/konversation.rb:6:in `class:Konversation'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/konversation.rb:6:in `class:Konversation'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/konversation.rb:6:in `class:Konversation'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/massif-visualizer.rb:6:in `class:MassifVisualizer'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/massif-visualizer.rb:6:in `class:MassifVisualizer'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/massif-visualizer.rb:6:in `class:MassifVisualizer'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/nepomuk-core.rb:6:in `class:NepomukCore'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/nepomuk-core.rb:6:in `class:NepomukCore'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/nepomuk-core.rb:6:in `class:NepomukCore'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/oxygen-icons.rb:6:in `class:OxygenIcons'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/oxygen-icons.rb:6:in `class:OxygenIcons'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/oxygen-icons.rb:6:in `class:OxygenIcons'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/shared-desktop-ontologies.rb:6:in `class:SharedDesktopOntologies'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/shared-desktop-ontologies.rb:6:in `class:SharedDesktopOntologies'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/shared-desktop-ontologies.rb:6:in `class:SharedDesktopOntologies'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/soprano.rb:6:in `class:Soprano'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/soprano.rb:6:in `class:Soprano'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/soprano.rb:6:in `class:Soprano'
Please report this to the adymo/kde tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/strigi.rb:6:in `class:Strigi'
Please report this to the adymo/kde tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/strigi.rb:6:in `class:Strigi'
Please report this to the adymo/kde tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/strigi.rb:6:in `class:Strigi'
Please report this to the adymo/kde tap!

formulae require at least a URL
Error: Cannot tap adymo/kde: invalid syntax in tap!

**Comment by qiukeren** [comment]
+1 for this bug

```
Error: Invalid formula: /usr/local/Library/Taps/adymo/homebrew-kde/base_kde_formula.rb
formulae require at least a URL
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/adymo/homebrew-kde/grantlee.rb:7:in `<class:Grantlee>'
Please report this to the adymo/kde tap!
```

**Comment by ales-tsurko** [comment]
Same here.

**Comment by lylemoffitt** [comment]
I've had this bug for a while now. It can also be reported by `brew dr`.

**Comment by ently** [comment]
+1 same issue here, OS X 10.12

**Comment by ronabraham** [comment]
still facing the issue.
